name: Hassfest

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  hassfest:
    name: Hassfest validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Run hassfest validation
        uses: home-assistant/actions/hassfest@master
